/* Generated by Yosys 0.35+58 (git sha1 8bd681acf, gcc 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */

(* top =  1  *)
(* src = "./benchmark/or.v:1.1-3.10" *)
module or_gate(a, b, y);
  (* src = "./benchmark/or.v:1.22-1.23" *)
  input a;
  wire a;
  (* src = "./benchmark/or.v:1.31-1.32" *)
  input b;
  wire b;
  (* src = "./benchmark/or.v:1.41-1.42" *)
  output y;
  wire y;
  assign y = 4'he >> { b, a };
endmodule
