/* Generated by Yosys 0.35+58 (git sha1 8bd681acf, gcc 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */

(* top =  1  *)
(* src = "./benchmark/and_gate.v:1.1-3.10" *)
module and_gate(a, b, y);
  (* src = "./benchmark/and_gate.v:1.23-1.24" *)
  input a;
  wire a;
  (* src = "./benchmark/and_gate.v:1.32-1.33" *)
  input b;
  wire b;
  (* src = "./benchmark/and_gate.v:1.42-1.43" *)
  output y;
  wire y;
  assign y = 4'h8 >> { b, a };
endmodule
